insert into main.Preferences (Category, Publisher, Account_ID)
values  ('Literature & Fiction', 'Vintage Books', 0),
        ('Fantasy', 'MIT Press', 1),
        ('Computer', 'O''Reilly & Associates', 2),
        ('Fantasy', 'Vintage Books', 3),
        ('Literature & Fiction', 'Anchor Books', 4),
        ('Fantasy', 'Vintage Books', 5),
        ('Home Design', 'Anchor Books', 6),
        ('Fantasy', 'Anchor Books', 7),
        ('Fantasy', 'Anchor Books', 8),
        ('Literature & Fiction', 'Vintage Books', 9),
        ('Home Design', 'O''Reilly & Associates', 10),
        ('Fantasy', 'Harper', 11),
        ('Science', 'Vintage Books', 12),
        ('Fantasy', 'Harper', 13),
        ('Science', 'Vintage Books', 14),
        ('Literature & Fiction', 'Anchor Books', 15),
        ('Science', 'Harper', 16),
        ('Literature & Fiction', 'Vintage Books', 17),
        ('Science', 'Anchor Books', 18),
        ('Literature & Fiction', 'Harper', 19),
        ('Literature & Fiction', 'MIT Press', 20),
        ('Science', 'Vintage Books', 21),
        ('Fantasy', 'Harper', 22),
        ('Computer', 'Harper', 23),
        ('Science', 'Harper', 24),
        ('Home Design', 'Anchor Books', 25),
        ('Home Design', 'O''Reilly & Associates', 26),
        ('Science', 'O''Reilly & Associates', 27),
        ('Fantasy', 'Vintage Books', 28),
        ('Science', 'MIT Press', 29),
        ('Fantasy', 'MIT Press', 30),
        ('Science', 'Anchor Books', 31),
        ('Literature & Fiction', 'O''Reilly & Associates', 32),
        ('Home Design', 'Vintage Books', 33),
        ('Literature & Fiction', 'Vintage Books', 34),
        ('Computer', 'Harper', 35),
        ('Computer', 'Harper', 36),
        ('Literature & Fiction', 'O''Reilly & Associates', 37),
        ('Fantasy', 'Vintage Books', 38),
        ('Science', 'Vintage Books', 39),
        ('Literature & Fiction', 'Anchor Books', 40),
        ('Computer', 'Anchor Books', 41),
        ('Home Design', 'Anchor Books', 42),
        ('Science', 'Harper', 43),
        ('Home Design', 'Harper', 44),
        ('Fantasy', 'Anchor Books', 45),
        ('Science', 'Vintage Books', 46),
        ('Home Design', 'Vintage Books', 47),
        ('Literature & Fiction', 'O''Reilly & Associates', 48),
        ('Computer', 'O''Reilly & Associates', 49);